CREATE TABLE IF NOT EXISTS TodoTagLinks (
    TagID INT NOT NULL,
    TodoID INT NOT NULL,
    FOREIGN KEY (TagID) REFERENCES Tags(ID),
    FOREIGN KEY (TodoID) REFERENCES Todos(ID),
    PRIMARY KEY (TagID, TodoID)
)